

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_ticketear
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_ORIGINS="*"
    volumes:
      - ./ollama_data:/root/.ollama
    